# First

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import sys
sys.path.append('../scripts')
from functions import *

from tqdm.notebook import tqdm

In [ ]:

molar_fractions_005 = get_molar_fractions(0.05, 5)

active_list_list = []
inactive_list_list = []
blocked_list_list = []

molar_fractions = molar_fractions_005
Vmin, Vmax, n_points = 0.1, 0.4, 13

for stoichiometry in tqdm(molar_fractions):
    
    HEA_surface = initialize_surface(dim_x, dim_y, metals, stoichiometry)
    
    # Predict energies on all sites for both adsorbates + mixed_sites
    HEA_surface = precompute_binding_energies_SPEED2(HEA_surface, dim_x, dim_y, models)
    
    # Calculate
    potential_range, active_list, inactive_list, blocked_list = counting_activity_scan(HEA_surface, Vmin, Vmax, n_points)
    active_list_list.append(active_list)
    inactive_list_list.append(inactive_list)
    blocked_list_list.append(blocked_list)

In [19]:
column_names = metals + ["Active", "Inactive", "Blocked"]
Ag_content = molar_fractions_005.T[0]
Au_content = molar_fractions_005.T[1]
Cu_content = molar_fractions_005.T[2]
Pd_content = molar_fractions_005.T[3]
Pt_content = molar_fractions_005.T[4]

for n, eU_string in enumerate([str(eU) for eU in np.linspace(Vmin, Vmax, n_points)]):
    write_to_csv("../Counting_Activity/All_Fracs005_eU"+eU_string+".csv", column_names, Ag_content, Au_content, Cu_content, Pd_content, Pt_content, np.array(active_list_list).T[n], np.array(inactive_list_list).T[n], np.array(blocked_list_list).T[n])

Data has been written to ../Counting_Activity/All_Fracs005_eU0.1.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.125.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.15000000000000002.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.17500000000000002.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.2.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.22500000000000003.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.25.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.275.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.30000000000000004.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.32500000000000007.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.3500000000000001.csv
Data has been written to ../Counting_Activity/All_Fracs005_eU0.3750000000000001.csv
Data has been written to ../Counting_Activity/All_Fracs00

In [17]:
Vmin, Vmax, n_points = 0.1, 0.4, 13
np.linspace(Vmin, Vmax, n_points)

array([0.1  , 0.125, 0.15 , 0.175, 0.2  , 0.225, 0.25 , 0.275, 0.3  ,
       0.325, 0.35 , 0.375, 0.4  ])

# Highly detailed version

In [7]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import sys
sys.path.append('../scripts')
from functions import *

from tqdm.notebook import tqdm

molar_fractions_005 = get_molar_fractions(0.05, 5)

active_list_list = []
inactive_list_list = []
blocked_list_list = []

molar_fractions = molar_fractions_005
Vmin, Vmax, n_points = 0.1, 0.35, 26

for stoichiometry in tqdm(molar_fractions):
    
    HEA_surface = initialize_surface(dim_x, dim_y, metals, stoichiometry)
    
    # Predict energies on all sites for both adsorbates + mixed_sites
    HEA_surface = precompute_binding_energies_SPEED2(HEA_surface, dim_x, dim_y, models)
    
    # Calculate
    potential_range, active_list, inactive_list, blocked_list = counting_activity_scan(HEA_surface, Vmin, Vmax, n_points)
    active_list_list.append(active_list)
    inactive_list_list.append(inactive_list)
    blocked_list_list.append(blocked_list)

  0%|          | 0/10626 [00:00<?, ?it/s]

In [8]:
column_names = metals + ["Active", "Inactive", "Blocked"]
Ag_content = molar_fractions_005.T[0]
Au_content = molar_fractions_005.T[1]
Cu_content = molar_fractions_005.T[2]
Pd_content = molar_fractions_005.T[3]
Pt_content = molar_fractions_005.T[4]

for n, eU_string in enumerate([str(eU) for eU in np.linspace(Vmin, Vmax, n_points)]):
    write_to_csv("../Counting_Activity/HighRes_All_Fracs005_eU"+eU_string+".csv", column_names, Ag_content, Au_content, Cu_content, Pd_content, Pt_content, np.array(active_list_list).T[n], np.array(inactive_list_list).T[n], np.array(blocked_list_list).T[n])

Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.1.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.11.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.12.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.13.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.14.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.15.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.16.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.16999999999999998.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.18.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.19.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.19999999999999998.csv
Data has been written to ../Counting_Activity/HighRes_All_Fracs005_eU0.21.csv
Data has been written to ../Countin

In [26]:
Vmin, Vmax, n_points = 0.1, 0.35, 21
np.linspace(Vmin, Vmax, n_points)

array([0.1   , 0.1125, 0.125 , 0.1375, 0.15  , 0.1625, 0.175 , 0.1875,
       0.2   , 0.2125, 0.225 , 0.2375, 0.25  , 0.2625, 0.275 , 0.2875,
       0.3   , 0.3125, 0.325 , 0.3375, 0.35  ])

In [6]:
Vmin, Vmax, n_points = 0.1, 0.35, 26
np.linspace(Vmin, Vmax, n_points)

array([0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
       0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31,
       0.32, 0.33, 0.34, 0.35])

In [31]:
molar_fractions_005 = get_molar_fractions(0.05, 5)
print(len(molar_fractions_005))

10626


# Run super high resolution JUST at the four potentials with big surfaces

For the first three, I can just use three metals at 1% molar fractions. The scaling is really forgiving at only 3 metals. 

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import sys
sys.path.append('../scripts')
from functions import *

from tqdm.notebook import tqdm

In [3]:
potential_range = np.array([0.31, 0.27, 0.21, 0.16])

molar_fractions_001_PtCuAu = get_molar_fractions(0.01, 3) # Put empty Pd and Ag columns/rows in here
# I have to add in a list of zeros at index 0 and 3
molar_fractions_001_PtCuAu = np.array([
    np.zeros(len(molar_fractions_001_PtCuAu)), # Ag, there is none of that
    molar_fractions_001_PtCuAu.T[0],           # Au
    molar_fractions_001_PtCuAu.T[1],           # Cu
    np.zeros(len(molar_fractions_001_PtCuAu)), # Pd, there is none of that
    molar_fractions_001_PtCuAu.T[2],           # Pt
]).T

molar_fractions_001_PtCuAg = get_molar_fractions(0.01, 3)
molar_fractions_001_PtCuAg = np.array([
    molar_fractions_001_PtCuAg.T[0],           # Ag
    np.zeros(len(molar_fractions_001_PtCuAg)), # Au, there is none of that
    molar_fractions_001_PtCuAg.T[1],           # Cu
    np.zeros(len(molar_fractions_001_PtCuAg)), # Pd, there is none of that
    molar_fractions_001_PtCuAg.T[2],           # Pt
]).T

molar_fractions_003_PtCuAgAu = get_molar_fractions(0.03, 4)
molar_fractions_003_PtCuAgAu = np.array([
    molar_fractions_003_PtCuAgAu.T[0],           # Ag
    molar_fractions_003_PtCuAgAu.T[1], # Au
    molar_fractions_003_PtCuAgAu.T[2],           # Cu
    np.zeros(len(molar_fractions_003_PtCuAgAu)), # Pd, there is none of that
    molar_fractions_003_PtCuAgAu.T[3],           # Pt
]).T

# 0.31 Optimum

In [4]:
active_list   = []
inactive_list = []
blocked_list  = []

for stoichiometry in tqdm(molar_fractions_001_PtCuAu):
    
    HEA_surface = initialize_surface(dim_x, dim_y, metals, stoichiometry)
    
    # Predict energies on all sites for both adsorbates + mixed_sites
    HEA_surface = precompute_binding_energies_SPEED2(HEA_surface, dim_x, dim_y, models)
    
    # Calculate
    active, inactive, blocked = counting_activity(HEA_surface, potential_range[0])
    active_list.append(active)
    inactive_list.append(inactive)
    blocked_list.append(blocked)

column_names = metals + ["Active", "Inactive", "Blocked"]
Ag_content = molar_fractions_001_PtCuAu.T[0]
Au_content = molar_fractions_001_PtCuAu.T[1]
Cu_content = molar_fractions_001_PtCuAu.T[2]
Pd_content = molar_fractions_001_PtCuAu.T[3]
Pt_content = molar_fractions_001_PtCuAu.T[4]

write_to_csv("../Counting_Activity/SUPERHighRes_031_optimum.csv", column_names, Ag_content, Au_content, Cu_content, Pd_content, Pt_content, active_list, inactive_list, blocked_list)

  0%|          | 0/5151 [00:00<?, ?it/s]

Data has been written to ../Counting_Activity/SUPERHighRes_031_optimum.csv


# 0.27 Optimum

In [5]:
active_list   = []
inactive_list = []
blocked_list  = []

for stoichiometry in tqdm(molar_fractions_001_PtCuAu):
    
    HEA_surface = initialize_surface(dim_x, dim_y, metals, stoichiometry)
    
    # Predict energies on all sites for both adsorbates + mixed_sites
    HEA_surface = precompute_binding_energies_SPEED2(HEA_surface, dim_x, dim_y, models)
    
    # Calculate
    active, inactive, blocked = counting_activity(HEA_surface, potential_range[1])
    active_list.append(active)
    inactive_list.append(inactive)
    blocked_list.append(blocked)

column_names = metals + ["Active", "Inactive", "Blocked"]
Ag_content = molar_fractions_001_PtCuAu.T[0]
Au_content = molar_fractions_001_PtCuAu.T[1]
Cu_content = molar_fractions_001_PtCuAu.T[2]
Pd_content = molar_fractions_001_PtCuAu.T[3]
Pt_content = molar_fractions_001_PtCuAu.T[4]

write_to_csv("../Counting_Activity/SUPERHighRes_027_optimum.csv", column_names, Ag_content, Au_content, Cu_content, Pd_content, Pt_content, active_list, inactive_list, blocked_list)

  0%|          | 0/5151 [00:00<?, ?it/s]

Data has been written to ../Counting_Activity/SUPERHighRes_027_optimum.csv


# 0.21 Optimum

In [6]:
active_list   = []
inactive_list = []
blocked_list  = []

for stoichiometry in tqdm(molar_fractions_001_PtCuAg):
    
    HEA_surface = initialize_surface(dim_x, dim_y, metals, stoichiometry)
    
    # Predict energies on all sites for both adsorbates + mixed_sites
    HEA_surface = precompute_binding_energies_SPEED2(HEA_surface, dim_x, dim_y, models)
    
    # Calculate
    active, inactive, blocked = counting_activity(HEA_surface, potential_range[2])
    active_list.append(active)
    inactive_list.append(inactive)
    blocked_list.append(blocked)

column_names = metals + ["Active", "Inactive", "Blocked"]
Ag_content = molar_fractions_001_PtCuAg.T[0]
Au_content = molar_fractions_001_PtCuAg.T[1]
Cu_content = molar_fractions_001_PtCuAg.T[2]
Pd_content = molar_fractions_001_PtCuAg.T[3]
Pt_content = molar_fractions_001_PtCuAg.T[4]

write_to_csv("../Counting_Activity/SUPERHighRes_021_optimum.csv", column_names, Ag_content, Au_content, Cu_content, Pd_content, Pt_content, active_list, inactive_list, blocked_list)

  0%|          | 0/5151 [00:00<?, ?it/s]

Data has been written to ../Counting_Activity/SUPERHighRes_021_optimum.csv


# 0.16 Optimum

In [7]:
active_list   = []
inactive_list = []
blocked_list  = []

for stoichiometry in tqdm(molar_fractions_003_PtCuAgAu):
    
    HEA_surface = initialize_surface(dim_x, dim_y, metals, stoichiometry)
    
    # Predict energies on all sites for both adsorbates + mixed_sites
    HEA_surface = precompute_binding_energies_SPEED2(HEA_surface, dim_x, dim_y, models)
    
    # Calculate
    active, inactive, blocked = counting_activity(HEA_surface, potential_range[3])
    active_list.append(active)
    inactive_list.append(inactive)
    blocked_list.append(blocked)

column_names = metals + ["Active", "Inactive", "Blocked"]
Ag_content = molar_fractions_003_PtCuAgAu.T[0]
Au_content = molar_fractions_003_PtCuAgAu.T[1]
Cu_content = molar_fractions_003_PtCuAgAu.T[2]
Pd_content = molar_fractions_003_PtCuAgAu.T[3]
Pt_content = molar_fractions_003_PtCuAgAu.T[4]

write_to_csv("../Counting_Activity/SUPERHighRes_016_optimum.csv", column_names, Ag_content, Au_content, Cu_content, Pd_content, Pt_content, active_list, inactive_list, blocked_list)

  0%|          | 0/7140 [00:00<?, ?it/s]

Data has been written to ../Counting_Activity/SUPERHighRes_016_optimum.csv


In [16]:
molar_fractions_005 = get_molar_fractions(0.05, 5)
print(len(molar_fractions_005))

10626
